import { type NextPage } from "next";
import Head from "next/head";
import MtgCard from "../components/MtgCard"

import { api } from "../utils/api";

const Home: NextPage = () => {

	const card = api.card.randomCard.useQuery()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
                    <MtgCard card={card}/>
      </main>
    </>
  );
};

export default Home;
