import { type NextPage } from "next";
import Head from "next/head";
import MtgCard from "../components/MtgCard"


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
                    <MtgCard/>
      </main>
    </>
  );
};

export default Home;
